# Generated by Django 4.2.7 on 2024-01-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_order_payment_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalbillamount',
            field=models.FloatField(default=0),
        ),
    ]
