# Generated by Django 4.2.7 on 2024-01-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_order_totalbillamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='paymentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petapp.payment'),
        ),
    ]
